### ISSUE TITLE
Spinlock::aquire

### ISSUE THREAD

**Issue by poutyface** [RusPiRo/ruspiro-lock#17]
This line:
https://github.com/RusPiRo/ruspiro-lock/blob/6ee378513dfa9a968eb0418a56507ae582f3c628/src/sync/spinlock.rs#L65

How about using spin_loop_hint() in loop ?
https://doc.rust-lang.org/std/sync/atomic/fn.spin_loop_hint.html

**Comment by 2ndTaleStudio** [comment]
Hey,
thanks for the hint. I've never thought about it, as the main target of the `ruspiro-*` crate family is the bare-metal arm aarch64 target architecture and I'm not aware of any built-in spin-loop-hint feature in those processors. However, as I've implemented the `sev` instruction when releasing the spinlock it might make sense to place a `wfe` inside the loop to get the waiting core into a low power consumption mode.

**Comment by poutyface** [comment]
> as the main target of the ruspiro-* crate family is the bare-metal arm aarch64 target architecture

OK, I got it.
spin_loop_hint just call `yield` instruction.
